### ISSUE TITLE
Playbook

### ISSUE THREAD

**Issue by nick773312** [EMnify/matrix-synapse-auto-deploy#7]
I tried making a playbook but when i put the stuff like username and then run the playbook code  I get a syntax error

**Comment by hugoShaka** [comment]
Hi,
Can you test the role with the playbook I wrote below ?
If it fails could you paste me your error and the ansible version you're using ?


```
---
- hosts: synapse
  become: yes

  vars:
    username: synapse
    git_repo: https://github.com/matrix-org/synapse/tarball/master
    hostname: 10.99.99.230
    enable_registration: true
    enable_registration_captcha: false
    recaptcha_private_key: YOURPRIVATEKEYHERE
    recaptcha_public_key: YOURPUBLICKEYHERE
    turn_shared_secret: YOURSHAREDSECRETHERE
    make_migration: true
    database_secret: YOURDATABASESECRETHERE
    absolute_path_certificate: /home/{{ username }}/.synapse/{{ hostname }}.tls.crt
    absolute_path_key: /home/{{ username }}/.synapse/{{ hostname }}.tls.key
    generate_DH_params: true   # Generate DH parameters
    DH_params_location: /etc/ssl/diffihellman.pem
    
  roles:
    - the_role_name

```
